language: php

sudo: false

php:
- 5.6
- 5.5
- 5.4
- hhvm

before_script:
- composer install --no-interaction

script:
- phpunit --coverage-text --coverage-html build/html --report-useless-tests

after_script:
- php vendor/bin/test-reporter --stdout > codeclimate.json
- "if [ \"$TRAVIS_PHP_VERSION\" == \"5.6\" ]; then curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports; fi"
