language: php

sudo: false

php:
- 5.6
  env: REPORT_COVERAGE=true
- 5.5
  env: REPORT_COVERAGE=false
- 5.4
  env: REPORT_COVERAGE=false
- hhvm
  env: REPORT_COVERAGE=false

before_script:
- composer selfupdate
- composer install --no-interaction

script:
- phpunit

after_script:
- php vendor/bin/test-reporter --stdout > codeclimate.json
- ./report-coverage.sh
